# Generated by Django 5.0.3 on 2024-05-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_bill_final_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='final_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
